package io.akka.uptimekuma.domain;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

/**
 * The badge, against what the source's own library produces.
 *
 * <p>The fixtures were generated by running that library, so this is a comparison rather than a
 * restatement: a badge is embedded in somebody else's page and its width, its colours and the
 * position of the divide are the whole of what it communicates, so an approximation would be
 * visible.
 */
class BadgeMakerTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();

  @TestFactory
  @SuppressWarnings("unchecked")
  List<DynamicTest> everyFixtureRendersByteForByte() throws Exception {
    List<Map<String, Object>> fixtures =
        MAPPER.readValue(
            BadgeMakerTest.class.getResourceAsStream("/badge-fixtures.json"), List.class);
    return fixtures.stream()
        .map(
            fixture ->
                DynamicTest.dynamicTest(
                    fixture.get("style") + ": " + fixture.get("label") + " / " + fixture.get("message"),
                    () ->
                        assertEquals(
                            fixture.get("svg"),
                            BadgeMaker.make(
                                (String) fixture.get("label"),
                                (String) fixture.get("message"),
                                (String) fixture.get("color"),
                                (String) fixture.get("labelColor"),
                                (String) fixture.get("style")))))
        .toList();
  }

  @Test
  void anUnknownStyleIsRefused() {
    IllegalArgumentException refusal =
        assertThrows(
            IllegalArgumentException.class,
            () -> BadgeMaker.make("Status", "Up", "#66c20a", null, "hexagonal"));
    assertEquals("Unknown badge style: 'hexagonal'", refusal.getMessage());
  }

  @Test
  void aWidthIsRoundedUpToTheNextOddNumber() {
    // Odd, so the text's midpoint lands on a half pixel and both sides align the same way.
    assertEquals(1, BadgeMaker.preferredWidthOf("", CharWidths.VERDANA_11) % 2);
    assertEquals(1, BadgeMaker.preferredWidthOf("Status", CharWidths.VERDANA_11) % 2);
    assertEquals(1, BadgeMaker.preferredWidthOf("A much longer label", CharWidths.VERDANA_11) % 2);
  }

  @Test
  void aNamedColourResolvesToItsHex() {
    assertEquals("#007ec6", BadgeMaker.toSvgColor("blue"));
    assertEquals("#4c1", BadgeMaker.toSvgColor("brightgreen"));
    assertEquals("#e05d44", BadgeMaker.toSvgColor("critical"));
    assertEquals("#9f9f9f", BadgeMaker.toSvgColor("lightgray"));
    assertEquals("#66c20a", BadgeMaker.toSvgColor("#66c20a"));
    assertEquals("#66c20a", BadgeMaker.toSvgColor("66c20a"));
  }

  @Test
  void luminanceDecidesWhetherTheTextIsWhiteOrDark() {
    assertTrue(BadgeMaker.brightness("#000000") <= 0.69);
    assertTrue(BadgeMaker.brightness("#ffffff") > 0.69);
    // Both of the palette's own status colours are dark enough to take white text; a pale one
    // takes dark text instead, which is why the threshold is part of the comparison rather than
    // a detail.
    assertTrue(BadgeMaker.make("Status", "Up", "#66c20a", null, "flat").contains("fill=\"#fff\""));
    assertTrue(BadgeMaker.make("Status", "Down", "#c2290a", null, "flat").contains("fill=\"#fff\""));
    assertTrue(BadgeMaker.make("Status", "Up", "#eeeeee", null, "flat").contains("fill=\"#333\""));
  }

  @Test
  void markupInALabelIsEscapedRatherThanRendered() {
    String svg = BadgeMaker.make("A <b>& B", "x\"y", "red", null, "flat");
    assertTrue(svg.contains("A &lt;b&gt;&amp; B"));
    assertTrue(svg.contains("x&quot;y"));
    assertTrue(svg.contains("aria-label=\"A &lt;b&gt;&amp; B: x&quot;y\""));
  }

  @Test
  void aCssKeywordResolvesToItsTriple() {
    assertEquals(3, CssKeywords.rgb("rebeccapurple").length);
    assertEquals(102, CssKeywords.rgb("rebeccapurple")[0]);
    assertEquals(null, CssKeywords.rgb("notacolour"));
  }
}
